---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_solo

platforms:  
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[mysql::server]
      - recipe[myapp_db::default]
    attributes:
      mysql:
        server_root_password: "rootpass"

