Vagrant.configure "2" do |config|

  config.vm.box = "vagrant-hackaton"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.cache.auto_detect = false
  config.cache.scope = :box

  config.vm.network :forwarded_port, guest: 3306, host: 3306

  config.vm.network "public_network"

  config.vm.provision :chef_solo do |chef|
   chef.add_recipe "apt"   
   chef.add_recipe "mysql::server"
   chef.add_recipe "myapp_db" 

    chef.json = {
     "mysql" => {
       "server_root_password" => "notasecret"
     }
    }
  end

end